name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org https://cache.thalheim.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.thalheim.io:3gANx3+SdDphvMmR6P3dqPZDKcIZC7XxU1n+cXAROaA=

      - name: Build cross-platform binaries
        run: |
          echo "Building cross-platform binaries..."
          nix build .#checks.x86_64-linux.cross-build --log-format bar-with-logs

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          cp result/* release-assets/
          cd release-assets

          # List what we're uploading
          echo "Files to upload:"
          ls -la

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd release-assets

          # Get the tag name from the ref
          TAG_NAME="${GITHUB_REF#refs/tags/}"

          # Create release if it doesn't exist
          gh release create "$TAG_NAME" --title "$TAG_NAME" --notes "" 2>/dev/null || true

          # Upload all binaries and checksums at once
          gh release upload "$TAG_NAME" * \
            --repo "${{ github.repository }}" \
            --clobber
